# Generated by Django 4.0.4 on 2022-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.CharField(default='', max_length=250),
        ),
    ]
